### ISSUE TITLE
Transfer plone.z3cform to plone org?

### ISSUE THREAD

**Issue by gforcada** [plone/buildout.coredev#139]
I just realized that plone.z3cform is not in plone github org but on zopefoundation one. Is there any reason not to move it over to plone github org?

**Comment by vincentfretin** [comment]
The plone.z3cform package is in the zope foundation since the beginning under the ZPL 2.1 license. The split plone.z3cform/plone.app.z3cform was to be able to use plone.z3cform outside of the Plone community.
If you move it to the Plone foundation, I think you need to keep the license, right?

**Comment by vincentfretin** [comment]
And if you move it to plone foundation, there is no sense to keep it separated from plone.app.z3cform. It should just be only one package plone.app.z3cform.

**Comment by gforcada** [comment]
:+1: I guess @esteele will be glad to merge two packages together

**Comment by gforcada** [comment]
@esteele @polyester any reason to hold back this fork? At the least we would be able to merge the translations together :-)

**Comment by polyester** [comment]
well, there's the licensing mess. The resulting merged package should come under a license, and that is messy in this case. See https://github.com/zopefoundation/plone.z3cform/issues/3

To further complicate matters, it sure looks like plone.z3cform was originally under GPL, and in the Plone repository. See http://svn.plone.org/svn/plone/plone.z3cform

Relicensing it under ZPL (in 2008) was never sanctioned by the Plone Foundation (I triple checked all Foundation archives) and was therefore **not** legal. Since then many people have contributed, all but one (https://github.com/zopefoundation/plone.z3cform/commits?author=mgedmin) of which have signed a PF Contrib Agreement btw. Yet the commits were done while in the zopefoundation repo, apparently (although in violation of the original copyright) under ZPL.

Of course, the merged code could be relicensed by the PF under ZPL, but that feels wrong in this case; it would make BSD even more 'viral' than GPL is often accused of. Given the history of the package, I'd lean towards GPL'ing a fork/merge, but that's just my personal opinion for now.

**Comment by thet** [comment]
you could ask @mgedmin if he is ok with relicensing or even signing the plone contributors agreement. he is still active and a reasonable guy :)

**Comment by mgedmin** [comment]
I'm fine with ZPL as a licence, and I expect the PF contrib agreement not to be any worse than the ZF one.

(I've a commit bit for the Plone Collective, and I'm surprised that I didn't need to sign any contrib agreements for that?)

**Comment by mauritsvanrees** [comment]
The Plone contributor agreement is explained and linked here:
http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html

The collective is for add-ons and is open to anyone without formal checks or agreements.  For the core we are more strict.

**Comment by mgedmin** [comment]
Actually, the one and only [commit](https://github.com/zopefoundation/plone.z3cform/commit/c9a6672caba8a69d98a45044bc3fdfbcf25784e6) I made to plone.z3cform was replacing a copy of zc.buildout's bootstrap.py with a newer copy of bootstrap.py. Do you really need a copyright assignment for that?

**Comment by jensens** [comment]
since the bootstrap.py has an own license this should not affect the overall licence.

**Comment by jensens** [comment]
So possible action (correct me if I'am wrong):

1. Move (fork) back to ``/plone`` (we can do this anyway, its open source)
2. assume the code is still IP of the PF (this is the question), 
3. anyway if (2) is true: since it was never activly relicensed by the IP owner to ZPL the GPL still sticks and so the code in fact is GPL!
4. Change the README and other places to point again to PF/GPL.

**Comment by petschki** [comment]
Hi ... since zopefoundation gets (or is already) assimilated is there a chance to get https://github.com/zopefoundation/plone.z3cform.git to /plone quick and easy? I'm willing to take care of any license changes if someone guides me. From a CI point of view this would be awesome because right now jenkins cannot run jobs with PR's from `p.z3cform` .... and merging `p.z3cform` and `p.a.z3cform` together seems not to be an easy task from a quick view through my omelette ...

**Comment by polyester** [comment]
I'd say, given the history of the package, it should move to /plone, via the steps laid out in @jensens [comment](https://github.com/plone/buildout.coredev/issues/139#issuecomment-269507635) from december 2016 above, so move it and re-set GPLv2 on it.

What I'm not sure about: I can *transfer* the package to /plone, but I'm not sure what will all break if that happens. Should we fork or transfer?
I know people shouldn't depend on unreleased versions in production buildouts, but they may do. 

So maybe it's wiser to fork/copy, and then put this one in ARCHIVE/READONLY status to make it clear it has moved.

Opinions from people wiser than me in release management?

**Comment by petschki** [comment]
ok let's be kind ... forking is the less offensive way doing this. So we need anyone who has rights to do so ... me not has enough 🤔 @jensens @polyester ?

Question: open PR's aren't forked, are they? If not, I'll open a new one on the forked `/plone` repo ... this can then be tested with jenkins ... hip hip 🎉

**Comment by mauritsvanrees** [comment]
Yes, forking sounds polite.
And edit the README.rst to point to the new canonical repository.
Possibly edit the github description to have that same information. (I have no rights to do that, but you can create an issue for that.)

**Comment by tisto** [comment]
Forking done: https://github.com/plone/plone.z3cform

**Comment by petschki** [comment]
hm ... could it be that the issue tracker is not available on forks? or can it be activated?

**Comment by tisto** [comment]
I activated the issue tracker.

**Comment by petschki** [comment]
@tisto thank you ... I just wanted to create a new branch on the fork but get a permission denied? Is there something missing?

**Comment by tisto** [comment]
@petschki try now.

**Comment by petschki** [comment]
@tisto working! thank's!

**Comment by icemac** [comment]
zopefoundation/plone.z3cform is now archived. Is there still anything to do or can this issue be closed now?

**Comment by petschki** [comment]
@icemac thank's! When my PR with license change got merged https://github.com/plone/plone.z3cform/pull/2 I'll close this issue too.

**Comment by petschki** [comment]
done!
