### ISSUE TITLE
Plone 4.3: plone.protect>=3.0.19

### ISSUE THREAD

**Issue by claytonc** [plone/buildout.coredev#313]
Requirement of plone4.csrffixes==1.1: plone.protect>=3.0.19

https://github.com/plone/buildout.coredev/blob/4.3/versions.cfg#L208

**Comment by mauritsvanrees** [comment]
We don't want to add `plone4.csrffixes` in Plone 4.3 core. There are too many tests that would go wrong because of it. Those should only need changes in the tests, not in real code, but it is too much effort.  So `plone.protect` will remain officially at version `2.x`.

`plone4.csrffixes` and `plone.protect 3.x` are still recommended.  Or you can edit your front webserver (likely nginx or Apache) to deny access to the `ZMI` at `manage` and `manage_*` urls.

For most customers I have blocked access to the ZMI. For a few I have added `plone4.csrffixes`.
