### ISSUE TITLE
Adding semantic versioning labels to github

### ISSUE THREAD

**Issue by tisto** [plone/buildout.coredev#433]
plone.restapi uses semantic versioning. Right now we use a combination of milestones and labels to mark issues and pull requests. Would it be possible to add some additional labels that we can use for semantic versioning? Something like:

1) Breaking Change
2) New Feature
3) Bugfix

This would make it a lot easier for me to plan new releases.

cc @jensens

**Comment by jensens** [comment]
+1

Is it ok to use the https://semver.org names MAJOR.MINOR.PATCH instead of introducing own names? Its also shorter.

I propose to add (all the same color of ``#a800ff`):
- ``51: target: patch``
- ``52: target: minor``
- ``53: target: major``

I added it to the sheet (RFC) at https://docs.google.com/spreadsheets/d/1IQ73bSQ10b0pwoUFn0u8SE4epDdvwjhTiYTDyPAhx7A

**Comment by mauritsvanrees** [comment]
Sounds good.

Note: when I make releases of Plone packages, I will *not* check to see which PRs have been merged and which target label has been attached. That is too much extra hassle.
