### ISSUE TITLE
Version constraint conflict

### ISSUE THREAD

**Issue by bsnizek** [plone/buildout.coredev#602]
Since about yesterday I get a version constraint conflict, both when I bootstrap towards Pyhon 2 and Python3.

```
  Requirement of z3c.caching: zope.interface>=3.8.0
While:
  Installing instance.
Error: The requirement ('Zope>=4.1.2') is not allowed by your [versions] constraint (4.1.1)
```

**Comment by mauritsvanrees** [comment]
All Jenkins 5.2 jobs are broken because of this.
See for example https://jenkins.plone.org/job/plone-5.2-python-2.7/305/console
In there, I see that Products.PythonScripts 5.0 now requires Zope 4.1.2.

An obvious thing to try it to change the [coredev 5.2 versions.cfg](https://github.com/plone/buildout.coredev/blob/5.2/versions.cfg#L5) to extend the [Zope 4.1.2 versions](https://raw.githubusercontent.com/zopefoundation/Zope/4.1.1/versions.cfg).
But when I try this locally, I get:

```
Installing instance.
Version and requirements information containing docutils:
  [versions] constraint on docutils: 0.15.2
  Requirement of Products.CMFCore: docutils<0.15
  Requirement of plone.app.theming: docutils
  Requirement of Products.CMFCore>=2.4.0: docutils<0.15
  Requirement of Products.CMFCore>=2.4.0dev: docutils<0.15
  Requirement of Products.CMFCore>=2.1: docutils<0.15
While:
  Installing instance.
Error: The requirement ('docutils<0.15') is not allowed by your [versions] constraint (0.15.2)
```

Okay, when I leave the Zope version at 4.1.1 and instead comment out the [checkout of Products.PythonScripts](https://github.com/plone/buildout.coredev/blob/5.2/checkouts.cfg#L23), the buildout finishes again.
Let me commit that so it is fixed for the moment, and let's try something better later.

**Comment by mauritsvanrees** [comment]
Okay, it seems we can pin docutils to 0.14 on Python 2.7, and then it works. Let me try a PR.
