### ISSUE TITLE
Segmentation fault on Jenkins since Zope 5.11

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/buildout.coredev#962]
I upgraded coredev 6.1 to Zope 5.11 today in https://github.com/plone/buildout.coredev/pull/959.  All tests were reported as green.  And indeed the robot tests passed, which is good news, but after that there was a [segmentation fault](https://jenkins.plone.org/job/pull-request-6.1-3.12/794/console).  Actually there were two segmentation faults, one when running the non-robot tests, and one after running the robot tests.

So Jenkins did not properly report a problem.  Maybe the segmentation fault is the cause.

As a start I will revert to Zope 5.10.

**Comment by mauritsvanrees** [comment]
You can trigger it with plone.app.testing:

```
$ bin/test -s plone.app.testing -u -t layers.rst
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:
    1/1 (100.0%)Segmentation fault: 11
```

```
$ bin/test -s plone.app.testing -u -t helpers.rst
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:
    1/1 (100.0%)Bus error: 10
```

**Comment by davisagli** [comment]
@mauritsvanrees Can't reproduce on my M1 Mac. Could you run the same command under gdb to get a C-level stack trace?

**Comment by mauritsvanrees** [comment]
I have not used `gdb` before, and don't have it installed.

But I tracked it down to `zope.interface`.  When I downgrade this to 6.3 the segfault is gone.  So it may be this problem:
https://github.com/zopefoundation/zope.interface/issues/323

When I checkout `zope.interface`, it works again.  But when I use tag 7.0.3 it also works.  So it can be that the C code is not used in this case.  I would need to look into how that works.

**Comment by davisagli** [comment]
@mauritsvanrees It's pretty simple, you just run `gdb [command]` and then if it segfaults you get more information.

Anyway, my money was on zope.interface. (Easy for me to place my bet after I know the answer!) There have been several different segfaults resulting from recent refactoring to support free-threading in Python 3.13. The most recent was just merged yesterday (https://github.com/zopefoundation/zope.interface/pull/324) but not yet released so I expect that's why it works when you use a checkout.

**Comment by mauritsvanrees** [comment]
This is fixed in `zope.interface` 7.1.1 which I include [here](https://github.com/plone/buildout.coredev/pull/964).
